spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realq?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  config:
    import: optional:application-secret.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    customCssUrl: /swagger-custom.css

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080

airkorea:
  api:
    service-key: ${AIRKOREA_API_KEY}

slack:
  token: ${SLACK_TOKEN}